### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by OpenSourceModular** [xsrf/easyeda-svg-import#12]
I don't know if this is an issue or expected behavior, but I thought I would post it anyways.
I am using inkscape 1.0.1

If I create a filled box, circle, hex, and then convert to paths they import as intended.
If I create the same object, but remove the fill and add the outline, they still import as filled.
If I draw a path with a bezier tool, i.e. a curved line, it imports it as filled.
If I draw a horizontal or vertical path, it does not import it at all.

(All items selected in Inkscape and converted to paths before saving).

Thanks!

![Screenshot from 2021-03-11 13-41-59](https://user-images.githubusercontent.com/80267981/110852518-b5529100-826f-11eb-8d3d-46aec64206a9.png)
![Screenshot from 2021-03-11 13-41-29](https://user-images.githubusercontent.com/80267981/110852531-b97eae80-826f-11eb-8ec0-fc550bed88c8.png)

**Comment by xsrf** [comment]
Hey, at first glance this is expected.
Imports as SVG nodes or solid regions are always closed filled shapes defined by the paths / outlines. This is why the curved line gets closed and the two straight lines probably got imported but are not visible (zero width).
If you import as Track instead, only the outlines will be imported as tracks. This will import the curved line and the straight lines correctly and imports the top shapes without fill.
There may be a way to convert the actual outlines of objects into paths, so that all shapes directly import as you expect. I'll have a look at that. I'm not really an expert with Inkscape.

**Comment by OpenSourceModular** [comment]
I see - that makes sense. No need for you to look into inkscape. I can come up with a workflow that suits my needs.

Thanks!

**Comment by xsrf** [comment]
Okay, confirmed. You may use **Stroke to Path** on all shapes except the first three to get the result you probably expected.
Basically, while shapes in Inkscape do have fill *and* stroke, in EasyEDA they are *either* fill (SVG Node, solid region) *or* stroke (Track). Hope that helps! I may add some of the examples you provided to the readme.

**Comment by OpenSourceModular** [comment]
Yes, I just experimented and found the same result - thanks!

**Comment by xsrf** [comment]
I've added some example screenshots to the readme:
<img src="https://github.com/xsrf/easyeda-svg-import/blob/0922e97f5414f6b3adaa944754f4e59c8bbe07f1/images/import_example.png?raw=true" >
