### ISSUE TITLE
error when loading extension

### ISSUE THREAD

**Issue by Nhouse111** [xsrf/easyeda-svg-import#19]
hello! thanks for this nice feature. unfortunately, i need a bit of help.

trying to load the files within the extension folder but i get a generic error
![Schermata 2021-08-09 alle 16 18 25](https://user-images.githubusercontent.com/77387018/128721550-6173a827-b1de-4443-a75b-cbfe778641b7.png)

any idea?

edit: i tried on browser and it works there.
4.4.20.6 is my easyeda version and i'm on OSX 10.12.6

**Comment by xsrf** [comment]
Hey, I assume you meant 6.4.20.6? Can you please have a look at #16 - maybe it's related? I don't have MacOS so it's hard for me to debug. I never got a response to the other issue. Maybe the altered version or an older version also works for you?

**Comment by Nhouse111** [comment]
Hello.
Correct. EasyEDA version is 6.4.20.6.
My OS is 10.12.6 Sierra.
On the browser is works correctly. Thanks for that.
on the software it still doesn't work.
the screenshot above shows up every time I log in and it appeared just after I hit the Load Extension button. (by keeping this, i'm still able to use it on the browser, that's fine for the moment.

by typing `navigator.userAgent` in "console", i get this :
![Schermata 2021-08-29 alle 18 47 31](https://user-images.githubusercontent.com/77387018/131258478-1ff46e08-b6fd-46bb-ad95-9e4d795e0d47.png)

**Comment by xsrf** [comment]
Hmm... It reports a pretty old version, which explains why the import fails. But I don't understand that. Have you tried uninstalling and reinstalling EasyEDA instead of updating it? I'm not familiar with the updating / installing process on Mac though... 

Btw. you can remove the extension from the app, it will still remain in the browser. The browser and desktop app extensions are completely independent.

**Comment by Nhouse111** [comment]
the issue disappeared, thanks for this very useful feature!!
