### ISSUE TITLE
Unknown commands in SVG

### ISSUE THREAD

**Issue by nygma2004** [xsrf/easyeda-svg-import#3]
I tried this with a SVG that I have converted from DWG using this page: https://anyconv.com/dwg-to-svg-converter/
I am getting an unknow commands found in SVG. Find the SVG file attached.
[m61_pcb_badge_window.zip](https://github.com/xsrf/easyeda-svg-import/files/5540882/m61_pcb_badge_window.zip)

**Comment by xsrf** [comment]
Thx! The issue is that the SVG uses `L x y x y x y` syntax for drawing lines instead of `L x y L x y L x y`. I'll have a look at that.
However, the SVG created by https://anyconv.com/dwg-to-svg-converter/ is also really bad. It is basically a rastered image, consisting of thousands of vertical lines. That's really bad. maybe other converters work better?

However, I've opened the SVG in Inkscape. Selected all paths (CTRL+A) and used "Path" - "Union" to merge them into a single path. Then saved it. The result is attached and also works with my import script. I hope its measurements are not messed up...
[m61_pcb_badge_window_union.zip](https://github.com/xsrf/easyeda-svg-import/files/5540988/m61_pcb_badge_window_union.zip)

**Comment by nygma2004** [comment]
OK, I need to keep looking. I have downloaded another DWG to SVG converter from the Microsoft store, but that is still causing the same error.
Let me ask you about the EasyEDA part: OK, I import the shape to the TopLayer, and that will make a copper area in that shape. But that will still not expose the copper. Are you putting the same shape on the TopSolderMask layer as well? I am asking because in the 3D view that area still not appear with the same color as a pad of a component. So it still does not appear to be properly exposed copper. Or your experience is different in this? Did you manufacture anything using this method so far?
Also do you have any tips how to easily align all these different shape to each other in EasyEDA?

**Comment by xsrf** [comment]
Yeah, you have to import the layer on TopSolderMask and TopCopper. I've done designs with exposed HASL (not plain copper) this way.
![2020-11-14 17_12_20-Window](https://user-images.githubusercontent.com/8081353/99151589-aa5e6a00-269c-11eb-9c96-8b236a728efb.png)

For alignment: As long as you import them to the same origin and don't move them they will all end up at the right place.
If you really need to shift them: Add a marker/cross at the left top and bottom right outside of your actual design to each layer. This way all layers will have the same XY bounding box when you select them and move them around.

**Comment by xsrf** [comment]
`L x y x y` syntax is now supported with a646cacdd6c580fab683a3b2a95288df78306ba3 but I won't recommend using it with the SVG created from the online converter. Drawing these thousands of lines in EasyEDA will cause the browser to freeze for minutes and I don't think the result will be usable in EasyEDA.

Have a look at the SVG your own with a simple text editor. You can see the difference easily. The `m61_pcb_badge_window_union.svg` has only one path-Tag containing the windows shape. The converted SVG `m61_pcb_badge_window.svg` has thousands of paths containing only simple rectangles.

**Comment by nygma2004** [comment]
OK, let me finalize my design and see how it works for me.

**Comment by xsrf** [comment]
@nygma2004 just FYI I've redone the complete code and now made a proper extension that is easier to use and permanently installed in EasyEDA
